export const movieList = [
    {
        country: "Россия",
        director: "Дмитрий Дьяченко",
        duration: 210,
        year: "2023",
        description: "Что, если Чебурашка на самом деле существует?",
        image: "http://klubmama.ru/uploads/posts/2022-09/1662416861_15-klubmama-ru-p-den-rozhdeniya-cheburashki-podelka-foto-15.png",
        trailerLink: "https://www.youtube.com/watch?v=ueExdWhHsJo",
        thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYjmFDp9B2utEbpPD32sp4eHLgsxUFx_zkQhshLxNtehs7SkJy0IvVri9a9_DR-JCsDxs&usqp=CAU",
        movieId: 12345,
        nameRU: "Чебурашка",
        nameEN: "Cheburashka"
    },
    {
        country: "Россия",
        director: "Дмитрий Дьяченко",
        duration: 210,
        year: "2023",
        description: "Что, если Чебурашка на самом деле существует?",
        image: "http://klubmama.ru/uploads/posts/2022-09/1662416861_15-klubmama-ru-p-den-rozhdeniya-cheburashki-podelka-foto-15.png",
        trailerLink: "https://www.youtube.com/watch?v=ueExdWhHsJo",
        thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYjmFDp9B2utEbpPD32sp4eHLgsxUFx_zkQhshLxNtehs7SkJy0IvVri9a9_DR-JCsDxs&usqp=CAU",
        movieId: 12345,
        nameRU: "Чебурашка",
        nameEN: "Cheburashka"
    },
    {
        country: "Россия",
        director: "Дмитрий Дьяченко",
        duration: 210,
        year: "2023",
        description: "Что, если Чебурашка на самом деле существует?",
        image: "http://klubmama.ru/uploads/posts/2022-09/1662416861_15-klubmama-ru-p-den-rozhdeniya-cheburashki-podelka-foto-15.png",
        trailerLink: "https://www.youtube.com/watch?v=ueExdWhHsJo",
        thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYjmFDp9B2utEbpPD32sp4eHLgsxUFx_zkQhshLxNtehs7SkJy0IvVri9a9_DR-JCsDxs&usqp=CAU",
        movieId: 12345,
        nameRU: "Чебурашка",
        nameEN: "Cheburashka"
    },
    {
        country: "Россия",
        director: "Дмитрий Дьяченко",
        duration: 210,
        year: "2023",
        description: "Что, если Чебурашка на самом деле существует?",
        image: "http://klubmama.ru/uploads/posts/2022-09/1662416861_15-klubmama-ru-p-den-rozhdeniya-cheburashki-podelka-foto-15.png",
        trailerLink: "https://www.youtube.com/watch?v=ueExdWhHsJo",
        thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYjmFDp9B2utEbpPD32sp4eHLgsxUFx_zkQhshLxNtehs7SkJy0IvVri9a9_DR-JCsDxs&usqp=CAU",
        movieId: 12345,
        nameRU: "Чебурашка",
        nameEN: "Cheburashka"
    },
    {
        country: "Россия",
        director: "Дмитрий Дьяченко",
        duration: 210,
        year: "2023",
        description: "Что, если Чебурашка на самом деле существует?",
        image: "http://klubmama.ru/uploads/posts/2022-09/1662416861_15-klubmama-ru-p-den-rozhdeniya-cheburashki-podelka-foto-15.png",
        trailerLink: "https://www.youtube.com/watch?v=ueExdWhHsJo",
        thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYjmFDp9B2utEbpPD32sp4eHLgsxUFx_zkQhshLxNtehs7SkJy0IvVri9a9_DR-JCsDxs&usqp=CAU",
        movieId: 12345,
        nameRU: "Чебурашка",
        nameEN: "Cheburashka"
    },
    {
        country: "Россия",
        director: "Дмитрий Дьяченко",
        duration: 210,
        year: "2023",
        description: "Что, если Чебурашка на самом деле существует?",
        image: "http://klubmama.ru/uploads/posts/2022-09/1662416861_15-klubmama-ru-p-den-rozhdeniya-cheburashki-podelka-foto-15.png",
        trailerLink: "https://www.youtube.com/watch?v=ueExdWhHsJo",
        thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYjmFDp9B2utEbpPD32sp4eHLgsxUFx_zkQhshLxNtehs7SkJy0IvVri9a9_DR-JCsDxs&usqp=CAU",
        movieId: 12345,
        nameRU: "Чебурашка",
        nameEN: "Cheburashka"
    },
  ];
